"""Criação da coluna isactive e profile_img

Revision ID: 06a47fe9ba77
Revises: 9e9ae5a6fb1a
Create Date: 2021-10-29 18:39:09.787341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a47fe9ba77'
down_revision = '9e9ae5a6fb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isactive', sa.Boolean(create_constraint = False), nullable=True))
        batch_op.add_column(sa.Column('profile_img', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_img')
        batch_op.drop_column('isactive')

    # ### end Alembic commands ###
