"""Criacao da entidade Topico

Revision ID: 2f7a2f275ca2
Revises: f5db3f633419
Create Date: 2021-12-16 14:21:13.869157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7a2f275ca2'
down_revision = 'f5db3f633419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receitaID', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['receitaID'], ['receitas.id'], name=op.f('fk_topico_receitaID_receitas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topico'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topico')
    # ### end Alembic commands ###
