"""A imagem pode ser null

Revision ID: 4129237e6ac9
Revises: d3db8fa89d32
Create Date: 2021-11-10 17:39:22.635786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4129237e6ac9'
down_revision = 'd3db8fa89d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
