"""Receitas

Revision ID: 41f5fac345d8
Revises: 06a47fe9ba77
Create Date: 2021-11-09 18:50:18.800517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f5fac345d8'
down_revision = '06a47fe9ba77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receitas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=False),
    sa.Column('tempo_preparo', sa.String(length=50), nullable=False),
    sa.Column('rendimento', sa.String(length=50), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], name=op.f('fk_receitas_userID_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receitas'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receitas')
    # ### end Alembic commands ###
