"""adicionei o atributo comentario_ativado na ntidade Receitas

Revision ID: 5b79670d0a78
Revises: 147787e0b4ce
Create Date: 2021-11-26 14:21:26.345409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b79670d0a78'
down_revision = '147787e0b4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario_ativado', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.drop_column('comentario_ativado')

    # ### end Alembic commands ###
