"""excluir os atributos name e img do usuario na entidade receitas

Revision ID: 5b949daff4c8
Revises: 1771d98a4a42
Create Date: 2021-11-25 18:47:55.696867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b949daff4c8'
down_revision = '1771d98a4a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_column('nameUser')
        batch_op.drop_column('imgUser')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imgUser', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('nameUser', mysql.VARCHAR(length=70), nullable=False))

    # ### end Alembic commands ###
