"""Entidade Comentario

Revision ID: 7ca4978bf64e
Revises: a3bd3d8beb10
Create Date: 2021-11-24 19:39:09.956230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca4978bf64e'
down_revision = 'a3bd3d8beb10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('receitaID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receitaID'], ['receitas.id'], name=op.f('fk_comentarios_receitaID_receitas')),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], name=op.f('fk_comentarios_userID_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comentarios'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    # ### end Alembic commands ###
