"""Criacao da entidade Ingrediente

Revision ID: 915c25eb37e7
Revises: a7dbc7cadda1
Create Date: 2021-12-08 16:32:22.283487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915c25eb37e7'
down_revision = 'a7dbc7cadda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingrediente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receitaID', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['receitaID'], ['receitas.id'], name=op.f('fk_ingrediente_receitaID_receitas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingrediente'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingrediente')
    # ### end Alembic commands ###
