"""mudanca de desc para descricao

Revision ID: a3bd3d8beb10
Revises: 4129237e6ac9
Create Date: 2021-11-12 17:49:01.223229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3bd3d8beb10'
down_revision = '4129237e6ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=False))
        batch_op.drop_column('desc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
