"""Criacao da entidade Avaliacao

Revision ID: a7dbc7cadda1
Revises: d7a33ebb57c6
Create Date: 2021-12-06 17:16:59.222866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7dbc7cadda1'
down_revision = 'd7a33ebb57c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('receitaID', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receitaID'], ['receitas.id'], name=op.f('fk_avaliacao_receitaID_receitas')),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], name=op.f('fk_avaliacao_userID_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avaliacao'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacao')
    # ### end Alembic commands ###
