"""Criacao da entidade Etapa

Revision ID: b43a2625241b
Revises: 915c25eb37e7
Create Date: 2021-12-08 19:35:45.728664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43a2625241b'
down_revision = '915c25eb37e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etapa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receitaID', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['receitaID'], ['receitas.id'], name=op.f('fk_etapa_receitaID_receitas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etapa'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etapa')
    # ### end Alembic commands ###
