"""adicionei um atributo para o usuario admin

Revision ID: d7a33ebb57c6
Revises: 5b79670d0a78
Create Date: 2021-11-30 17:33:28.361048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a33ebb57c6'
down_revision = '5b79670d0a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isadmin', sa.Boolean(create_constraint = False), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('isadmin')

    # ### end Alembic commands ###
